# These are supported funding model platforms

github: [Gowixx, MineSearchIn, NotSkid100Percent, SecksMaster2]
patreon: MineSearch
open_collective: OpenCollective
ko_fi: KoFiChingChang
tidelift: npm/babel
community_bridge: cloud-foundry
liberapay: paymepls
issuehunt: IssueHuntOfficial
otechie: RealAdmin
custom: ['https://didntask.com', 'https://minesearch.in']
